# This is a basic workflow that is manually triggered

name: Compile and publish

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  repository_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  runProgram:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
        - name: Checkout Repository
          uses: actions/checkout@v4
          with:
            submodules: true
            ref: 'master'
            path: 'repo_ecommons'
        - name: Checkout Repository 2
          uses: actions/checkout@v4
          with:
            repository: 'NightmareXIV/NightmareXIVNugetUploader'
            submodules: true
            ref: 'main'
            path: 'repo_updater'
        - name: Set up .NET
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: 10.0.x
        - name: XDTesting Print Directory Structure
          uses: FiorelaCiroku/XDTesting-Print-Directory-Structure@v1.0.2
        - name: Run the program
          run: dotnet run --project ECommons/ECommons/repo_updater/NightmareXIVNugetUploader.csproj
          env: 
            TEST: true
